use robert5to7;
show tables;
desc student;
select * from student;
insert into student values(3,'oral','robert',7304795512,'mumbai');
alter table student auto_increment=100;
insert into student (fname,lname,contact,city) values('oral','robert',7304795593,'mumbai');
insert into student (fname,lname,contact,city) values('abhishek','jagtab',72832666776,'mumbai');
update student set fname='regi',lname='nair' where roll_no = 103;
select * from student order by roll_no desc;
select * from student order by roll_no;
update student set roll_no = 109 where contact=7304795586;
delete from student where roll_no = 1;
select student.lname, student.contact from student;
select fname, lname from student;
select * from first;
select fname as first_name, lname as last_name from student;
create table learn (Roll_no int, name varchar(20)not null);
show table status;
insert into learn values(1,'robert'),(2,'oral'),(3,'joel'),(4,'willbert');
select * from learn;
alter table learn auto_increment=100;
insert into learn (name)values('abhishek'),('nadar'),('ashish');
drop table learn;
create table learn(id int primary key,name varchar(20) not null,city varchar(20));
desc learn;
alter table learn add column state varchar(20) default ('maharashtra');
insert into learn (id,name,city) values('1','robert','mumbai');
insert into learn (id,name,city) values('3','nadar','mumbai');
insert into learn (id,name,city) values('4','abhishek','mumbai');
update learn set name = "oral" where id = 2;
update learn set city = "chennai" where id = 2;
update learn set state = "Tamil nadu" where id = 2;
insert into learn (id,name,city) values(5,'ashish','mumbai');
insert into learn (id,name,city) values(6,'ashish','mumbai'),(7,'swetha','mumbai');
delete from learn where id = 6;
alter table learn drop state;
select * from learn;
alter table learn add column state varchar(20)not null;
alter table learn drop maharashtra;
alter table learn modify id int null;
desc learn;